import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  jobs: [
    {
      id: 1,
      logo: 'logo1.png',
      title: 'Frontend Developer',
      company: 'Google',
      experience: 2,
      skills: ['JavaScript', 'React', 'CSS'],
      description: 'Lorem ipsum dolor sit amet.',
      applied: false,
      application: null,
    },
    {
      id: 2,
      logo: 'logo2.png',
      title: 'Backend Developer',
      company: 'Apple',
      experience: 3,
      skills: ['Node.js', 'Express', 'MongoDB'],
      description: 'Lorem ipsum dolor sit amet.',
      applied: false,
      application: null,
    },
    {
        id: 3,
        logo: 'logo3.png',
        title: 'Full Stack Developer',
        company: 'Netflix',
        experience: 4,
        skills: ['JavaScript', 'React', 'Node.js', 'Express', 'MongoDB'],
        description: 'Lorem ipsum dolor sit amet.',
        applied: false,
        application: null,
      },
      {
        id: 4,
        logo: 'logo4.png',
        title: 'ROR Developer',
        company: 'ZOHO',
        experience: 5,
        skills: ['Python', 'Pandas', 'NumPy', 'Machine Learning'],
        description: 'Lorem ipsum dolor sit amet.',
        applied: false,
        application: null,
      },
      {
        id: 5,
        logo: 'logo5.png',
        title: 'DevOps Engineer',
        company: 'META',
        experience: 3,
        skills: ['Docker', 'Kubernetes', 'CI/CD', 'AWS'],
        description: 'Lorem ipsum dolor sit amet.',
        applied: false,
        application: null,
      },
      {
        id: 6,
        logo: 'logo6.png',
        title: 'Cloud Architect',
        company: 'Flipkart',
        experience: 7,
        skills: ['AWS', 'Azure', 'GCP', 'Cloud Computing'],
        description: 'Lorem ipsum dolor sit amet.',
        applied: false,
        application: null,
      },
      {
        id: 7,
        logo: 'logo7.png',
        title: 'Database Administrator',
        company: 'Amazon',
        experience: 4,
        skills: ['SQL', 'NoSQL', 'Oracle DB', 'MySQL'],
        description: 'Lorem ipsum dolor sit amet.',
        applied: false,
        application: null,
      },
      {
        id: 8,
        logo: 'logo8.png',
        title: 'Cybersecurity Specialist',
        company: 'Freshworks',
        experience: 6,
        skills: ['Penetration Testing', 'Ethical Hacking', 'Cryptography'],
        description: 'Lorem ipsum dolor sit amet.',
        applied: false,
        application: null,
      },
      {
        id: 9,
        logo: 'logo9.png',
        title: 'Blockchain Developer',
        company: 'Kissflow',
        experience: 3,
        skills: ['Blockchain', 'Ethereum', 'Solidity', 'Smart Contracts'],
        description: 'Lorem ipsum dolor sit amet.',
        applied: false,
        application: null,
      },
      {
        id: 10,
        logo: 'logo10.png',
        title: 'Machine Learning Engineer',
        company: 'V Dart',
        experience: 5,
        skills: ['Python', 'TensorFlow', 'PyTorch', 'Machine Learning'],
        description: 'Lorem ipsum dolor sit amet.',
        applied: false,
        application: null,
      },
      {
        id: 11,
        logo: 'logo11.png',
        title: 'Mobile App Developer',
        company: 'MacAppStudio',
        experience: 4,
        skills: ['Swift', 'Kotlin', 'React Native'],
        description: 'Lorem ipsum dolor sit amet.',
        applied: false,
        application: null,
      },
      {
        id: 12,
        logo: 'logo12.png',
        title: 'Systems Analyst',
        company: 'Pepul',
        experience: 3,
        skills: ['Systems Analysis', 'Business Analysis', 'SQL'],
        description: 'Lorem ipsum dolor sit amet.',
        applied: false,
        application: null,
      },
      {
        id: 13,
        logo: 'logo13.png',
        title: 'Embedded Systems Engineer',
        company: 'SNA',
        experience: 5,
        skills: ['C', 'C++', 'Embedded Systems', 'Microcontrollers'],
        description: 'Lorem ipsum dolor sit amet.',
        applied: false,
        application: null,
      }
  ],
  skills: [
    'JavaScript', 'React', 'Node.js', 'Express', 'MongoDB', 'CSS', 'HTML', 'Redux', 'TypeScript',
    'Python', 'Django', 'Flask', 'Java', 'Spring', 'Hibernate', 'C++', 'SQL', 'NoSQL', 'GraphQL',
    'Docker', 'Kubernetes', 'AWS', 'Azure', 'GCP', 'Git', 'Linux', 'Agile', 'Scrum', 'C', 'C#',
    'PHP', 'Laravel', 'Symfony', 'Ruby', 'Ruby on Rails', 'Perl', 'Rust', 'Go', 'Scala', 'Swift',
    'Objective-C', 'Kotlin', 'R', 'MATLAB', 'Shell Scripting', 'Bash', 'PowerShell', 'Ansible',
    'Terraform', 'Puppet', 'Chef', 'Jenkins', 'CI/CD', 'Nagios', 'Prometheus', 'Grafana', 'Splunk',
    'ELK Stack', 'Firebase', 'Heroku', 'DigitalOcean', 'OpenStack', 'VMware', 'Hyper-V', 'Vagrant',
    'PostgreSQL', 'MySQL', 'MariaDB', 'Oracle DB', 'SQLite', 'Cassandra', 'Redis', 'Memcached',
    'Neo4j', 'Hadoop', 'Spark', 'Kafka', 'RabbitMQ', 'ActiveMQ', 'Zookeeper', 'ElasticSearch',
    'Logstash', 'Kibana', 'Tableau', 'Power BI', 'QlikView', 'SAS', 'SPSS', 'TensorFlow', 'Keras',
    'PyTorch', 'scikit-learn', 'NumPy', 'Pandas', 'Matplotlib', 'Seaborn', 'NLTK', 'OpenCV',
    'NLU', 'NLP', 'Deep Learning', 'Machine Learning', 'Data Science', 'Data Engineering', 
    'Data Analytics', 'Big Data', 'Business Intelligence', 'Cybersecurity', 'Information Security',
    'Penetration Testing', 'Ethical Hacking', 'Cryptography', 'Blockchain', 'Smart Contracts',
    'Solidity', 'Ethereum', 'Bitcoin', 'Hyperledger', 'IoT', 'Arduino', 'Raspberry Pi', 'Embedded Systems',
    'Microcontrollers', 'FPGA', 'VHDL', 'Verilog', 'ASIC Design', 'SystemVerilog', 'Cloud Computing',
    'DevOps', 'Site Reliability Engineering (SRE)', 'Software Development Life Cycle (SDLC)',
    'Test Driven Development (TDD)', 'Behavior Driven Development (BDD)', 'Unit Testing', 'Integration Testing',
    'System Testing', 'Acceptance Testing', 'JIRA', 'Confluence', 'Asana', 'Trello', 'MS Project', 'SharePoint',
    'SAP', 'Salesforce', 'Oracle ERP', 'Workday', 'ServiceNow', 'ITIL', 'COBIT', 'TOGAF', 'Six Sigma', 'Lean',
    'Project Management', 'Program Management', 'Product Management', 'Business Analysis', 'Systems Analysis'
  ],
};

const jobsSlice = createSlice({
  name: 'jobs',
  initialState,
  reducers: {
    applyForJob: (state, action) => {
      const { jobId, application } = action.payload;
      const job = state.jobs.find(job => job.id === jobId);
      if (job) {
        job.applied = true;
        job.application = application;
      }
    },
  },
});

export const { applyForJob } = jobsSlice.actions;

export default jobsSlice.reducer;
